#### General
profile=high-quality
#gpu-api=opengl  # Uncomment this if you notice stuttering with vulkan
gpu-api=vulkan  # Comment this if you notice stuttering and uncomment the above line
cursor-autohide=2500
keep-open=yes
force-window=yes
msg-module
msg-color
keepaspect

#DV File Settings uncomment as needed
tone-mapping=bt.2446a
vo=gpu-next
hwdec=no

#### OSD/OSC
osc=yes
osd-bar=no
osd-font="Fira Sans"
osd-bold=yes

#### Window
# autofit-larger=1920x1080
# force-window-position=yes
# fs=yes
border=no

#### Priority
slang=ja,jp,jpn,en,eng
alang=ja,jp,jpn,en,eng

#### Video
# Also includes all the filtering-related flags
#vo=gpu
#audio-display=embedded-first

# Streaming
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
hls-bitrate=max
ytdl-format=bestvideo[height<=?1440]+bestaudio/bestvideo+bestaudio/best
ytdl-raw-options=ignore-errors=
load-unsafe-playlists=yes

# Shaders
# Luma Up
glsl-shader="~~/shaders/ArtCNN_C416.glsl"
#glsl-shader="~~/shaders/ArtCNN_C432.glsl"
scale=ewa_lanczos
scale-blur=0.981251

# Luma Down
dscale=catmull_rom

# Chroma Up and Down
#glsl-shader="~~/shaders/ArtCNN_C432_Chroma.glsl"

# Dither
dither=error-diffusion
dither-depth=auto
error-diffusion=sierra-lite

# Antiring
scale-antiring=0.5
dscale-antiring=0.5
cscale-antiring=0.5

# Deband
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4

# RefreshRate
video-sync=display-resample
#override-display-fps=143.856

#### Audio
audio-file-auto=fuzzy
audio-pitch-correction=yes
volume=100
volume-max=100


## Subs
# Settings for text-based subtitle files (ASS, SRT)
# This style is an approximation of the GJM_Main dialogue style
### NOTE: Currently disabled while I try and sort it into profiles
sub-ass-override=no # Toggle with 'k'
sub-ass-force-style=playresx=1920,playresy=1080
sub-font="LTFinnegan Medium"
sub-font-size=38
sub-color="#FFFFFF"
sub-border-size=1.8
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
#sub-pos=90
sub-ass
sub-bold=no
#sub-ass-force-style=Kerning=yes

# Settings for image-based subtitle files (PGS, SUP)
#sub-gray
sub-gauss=0.05

# Other general settings
demuxer-mkv-subtitle-preroll=yes
#sub-ass-vsfilter-blur-compat=no
sub-fix-timing=no
msg-level=all=trace
save-position-on-quit=yes
#sub-font-provider=none
#embeddedfonts=no

# Auto subtitle file pathing
sub-auto=fuzzy
sub-file-paths-append=ass
sub-file-paths-append=srt
sub-file-paths-append=pgs
sub-file-paths-append=vob
sub-file-paths-append=sub
sub-file-paths-append=sup
sub-file-paths-append=subs
sub-file-paths-append=subtitles


#### Screenshots
screenshot-format=png
screenshot-high-bit-depth=no
screenshot-tag-colorspace=yes
screenshot-png-compression=2
screenshot-directory="~/Pictures/mpv-screenshots"
screenshot-template="%F-%03n" 

[extension.bmp]
profile=ww-ext-image
[extension.gif]
profile=ww-ext-image
[extension.jpeg]
profile=ww-ext-image
[extension.jpg]
profile=ww-ext-image
[extension.png]
profile=ww-ext-image
[extension.tif]
profile=ww-ext-image
[extension.tiff]
profile=ww-ext-image
[extension.webp]
profile=ww-ext-image


